create_james_package <- function(path, copyright_holder = "James Wade") {
  path <- create_package(path, rstudio = TRUE, open = FALSE)
  local_project(path)
  use_testthat()
  use_mit_license(copyright_holder)
  use_tidy_description()
  use_readme_rmd(open = FALSE)
  use_lifecycle_badge("experimental")
  use_cran_badge()
  use_cran_comments(open = FALSE)
  ui_todo("In the new package, remember to do:")
  ui_todo("{ui_code('use_git()')}")
  ui_todo("{ui_code('use_github()')}")
  ui_todo("{ui_code('use_tidy_github()')}")
  ui_todo("{ui_code('use_tidy_github_actions()')}")
  ui_todo("{ui_code('use_tidy_github_labels()')}")
  ui_todo("{ui_code('use_pkgdown_github_pages()')}")
  proj_activate(path)
}
